### ISSUE TITLE
restore window on double click

### ISSUE THREAD

**Issue by yeKcim** [franglais125/no-title-bar#35] opened 2017-10-19 12:00 UTC
copy of https://github.com/deadalnix/pixel-saver/issues/111#issue-219984408:

> Currently, a maximized window can only be resized on clicking the restore window button, dragging on the TopBar or with keyboard shortcuts. 😟 However, "restore on double click" would be a much more natural way to restore windows and consistent with the "maximize on double click" behavior. This is especially helpful for distros like Ubuntu GNOME that by default doesn't have maximize and minimize buttons, but only close button on the app window.
> 
> Video showing the expected working after this feature's implemented: [Link to Video](https://plus.google.com/photos/photo/104644865683307981392/6405951492490060306)

In fact, right clic and middle clic actions, could also be applied…

**Comment by franglais125** [comment] 2017-10-19 15:24
Thanks a lot for your input! I'll close this one as it's a duplicate of https://github.com/franglais125/no-title-bar/issues/27

Patches welcome, otherwise I'll have a look when I have some time, as this is something I personally would like to have as well :).

**Closed by franglais125** 2017-10-19 15:24 UTC
