### ISSUE TITLE
xprop zombie process on guake open/close

### ISSUE THREAD

**Issue by Mentis** [franglais125/no-title-bar#7] opened 2017-08-05 07:46 UTC
When this extension is enabled gnome-session creates zombie xprop process on guake open/close.
Cant reproduce this with Pixel Saver.

**Comment by franglais125** [comment] 2017-08-05 17:06
Thank you for reporting this. I'll look into it as soon as I find some time!

**Comment by franglais125** [comment] 2017-08-05 18:10
Is there a specific way of triggering this? It seems I can't reproduce it. I'll keep trying though.

1) Is this on X or Wayland?
2) What distribution and Shell version are you using?
3) Some specific steps etc?

Again, thanks for the input!

**Comment by Mentis** [comment] 2017-08-07 04:58
I can reproduce this reliably
Here is my specs:
1. X
2. Ubuntu 17.10 with gnome staging ppa (gnome 3.25)
3. Minimize/Maximize any window, open/close guake.  

I really like your addon over pixel saver: it support multiple monitors.
Thank you!

**Comment by franglais125** [comment] 2017-08-07 14:11
Ok, I managed to reproduce this on Gnome 3.25. It seems that 3.22 is unaffected, hence why I coouldn't see the issue.

I'll look into it. Thanks!

**Comment by franglais125** [comment] 2017-08-07 15:04
I've found the cause of the problem, and reverted the commit that caused it. Can someone confirm that the problem is fixed?

To do so:
```
git clone https://github.com/franglais125/no-title-bar
cd no-title-bar/
make install
```

And restart the session.

@jhasse Apologies for reverting your commit [03cfa652acf1fec617db8a36524a81c1ba1d9f9b]. I'll try and see how to work around this.

Thanks to everyone involved!

**Comment by Mentis** [comment] 2017-08-07 15:28
That's resolved the issue. Cant reproduce anymore. Thank you!

**Comment by franglais125** [comment] 2017-08-07 15:52
Hey @Mentis and @jhasse, I'll bother just once more.

I updated master with [36050af49d89d923131c4b6f0a7387007345dfa0]. I think we can now have the workaround by @jhasse, while not creating zombie processes.

Would you mind testing again? We can close the issue if this is successful.

**Comment by jhasse** [comment] 2017-08-07 15:55
Seems to work :)

**Comment by Mentis** [comment] 2017-08-07 15:56
Cant repro xprop issue on latest build.
Thanks!

**Comment by franglais125** [comment] 2017-08-07 19:23
Great! Thanks a lot you both! I'll rewrite history a bit, since the last 2 commits are just messy (in case you decide to `git pull`).

**Closed by franglais125** 2017-08-07 19:23 UTC
